# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Test
        uses: CultureHQ/actions-yarn@master
        with:
          args: coverage
      - name: Svelte-check
        uses: CultureHQ/actions-yarn@master
        with:
          args: validate
